# Generated by Django 6.0 on 2026-03-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_id_alter_variation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
