# Generated by Django 6.0 on 2026-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_reviewrating_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
