# Generated by Django 5.2.4 on 2026-01-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_quantity_cartitem_quantity'),
        ('store', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
